const express=require('express');
const cors=require('cors');
const multer=require('multer');
const XLSX=require('xlsx');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');
const bcrypt=require('bcryptjs');

const app=express();
app.set('trust proxy',1);
const PORT=process.env.PORT||3000;
const uploadDir=path.join(__dirname,'uploads');fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir});
const DATABASE_URL=process.env.DATABASE_URL||'';
const useDb=!!DATABASE_URL;
const pool=useDb?new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
const DATA_DIR=path.join(__dirname,'data');fs.mkdirSync(DATA_DIR,{recursive:true});
function readLocal(n,f=[]){try{return JSON.parse(fs.readFileSync(path.join(DATA_DIR,n),'utf8'))}catch{return f}}
function writeLocal(n,d){fs.writeFileSync(path.join(DATA_DIR,n),JSON.stringify(d,null,2),'utf8')}
const norm=s=>String(s||'').trim().replace(/\s+/g,' ');
const validPin=p=>/^\d{4}$/.test(String(p||''));
const validMobile=m=>/^\d{10}$/.test(String(m||''));
function validFullName(v){const s=norm(v);if(!/^[\p{L} ]+$/u.test(s))return false;const p=s.split(' ');return p.length>=2&&p.every(x=>[...x].length>=2)}
function studentPublic(x){return{id:x.id,name:x.name,fatherName:x.father_name??x.fatherName,mobile:x.mobile,pinSet:!!(x.pin_hash??x.pinHash)}}
function clampInt(v,min,max,def){const n=parseInt(v,10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):def}
function examPublic(x){return{id:Number(x.id),name:x.name,startAt:x.start_at??x.startAt??null,endAt:x.end_at??x.endAt??null,timerMode:x.timer_mode??x.timerMode??'none',durationMinutes:Number(x.duration_minutes??x.durationMinutes??0),perQuestionSeconds:Number(x.per_question_seconds??x.perQuestionSeconds??0),questionLimit:Number(x.question_limit??x.questionLimit??0),passingPercentage:Number(x.passing_percentage??x.passingPercentage??40),attemptLimit:Number(x.attempt_limit??x.attemptLimit??0),randomQuestions:!!(x.random_questions??x.randomQuestions),active:!!x.active}}
async function verifyStudent(mobile,pin){mobile=norm(mobile);if(!validMobile(mobile)||!validPin(pin))return null;if(useDb){const q=await pool.query('SELECT id,name,father_name,mobile,pin_hash FROM students WHERE mobile=$1',[mobile]);if(!q.rowCount||!q.rows[0].pin_hash)return null;return await bcrypt.compare(String(pin),q.rows[0].pin_hash)?q.rows[0]:null}const x=readLocal('students.json').find(s=>String(s.mobile)===mobile);if(!x||!x.pinHash)return null;return await bcrypt.compare(String(pin),x.pinHash)?x:null}
function nowStatus(e){const now=Date.now(),s=e.startAt?new Date(e.startAt).getTime():null,en=e.endAt?new Date(e.endAt).getTime():null;if(!e.active)return'inactive';if(s&&now<s)return'upcoming';if(en&&now>en)return'ended';return'available'}
function randomToken(){return crypto.randomBytes(24).toString('hex')}


const ADMIN_COOKIE='cie_admin_session';
const SESSION_TTL_MS=8*60*60*1000;
const SESSION_SECRET=process.env.ADMIN_SESSION_SECRET||crypto.randomBytes(32).toString('hex');
if(!process.env.ADMIN_SESSION_SECRET)console.warn('ADMIN_SESSION_SECRET is not set; admin sessions will reset on service restart.');
function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)out[decodeURIComponent(p.slice(0,i).trim())]=decodeURIComponent(p.slice(i+1).trim())});return out}
function signAdminToken(adminId){const payload=Buffer.from(JSON.stringify({adminId,exp:Date.now()+SESSION_TTL_MS})).toString('base64url');const sig=crypto.createHmac('sha256',SESSION_SECRET).update(payload).digest('base64url');return payload+'.'+sig}
function verifyAdminToken(token){try{const [payload,sig]=String(token||'').split('.');if(!payload||!sig)return null;const expected=crypto.createHmac('sha256',SESSION_SECRET).update(payload).digest('base64url');if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;const obj=JSON.parse(Buffer.from(payload,'base64url').toString('utf8'));if(!obj.adminId||Date.now()>obj.exp)return null;return obj}catch{return null}}
function setAdminCookie(res,adminId){res.cookie(ADMIN_COOKIE,signAdminToken(adminId),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:SESSION_TTL_MS,path:'/'})}
function clearAdminCookie(res){res.clearCookie(ADMIN_COOKIE,{path:'/'})}
function currentAdmin(req){return verifyAdminToken(parseCookies(req)[ADMIN_COOKIE])}
function requireAdmin(req,res,next){const a=currentAdmin(req);if(!a)return res.status(401).json({error:'Admin login required.'});req.admin=a;next()}
async function sendAdminResetEmail(to,resetUrl){const key=process.env.RESEND_API_KEY||'';const from=process.env.ADMIN_FROM_EMAIL||'CIE Exam <onboarding@resend.dev>';if(!key)throw new Error('Email recovery is not configured yet. Add RESEND_API_KEY in Render Environment.');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{'Authorization':'Bearer '+key,'Content-Type':'application/json'},body:JSON.stringify({from,to,subject:'CIE Exam Admin Password Reset',html:`<p>A password reset was requested for the CIE Exam Admin Portal.</p><p><a href="${resetUrl}">Reset Admin Password</a></p><p>This link expires in 20 minutes. If you did not request this, ignore this email.</p>`})});if(!r.ok){const t=await r.text();throw new Error('Could not send reset email: '+t)}}

async function initDb(){if(!useDb)return;await pool.query(`
CREATE TABLE IF NOT EXISTS students(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,father_name TEXT NOT NULL,mobile TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());
ALTER TABLE students ADD COLUMN IF NOT EXISTS pin_hash TEXT;
CREATE TABLE IF NOT EXISTS exams(
 id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,start_at TIMESTAMPTZ,end_at TIMESTAMPTZ,
 timer_mode TEXT NOT NULL DEFAULT 'none',duration_minutes INTEGER NOT NULL DEFAULT 0,
 per_question_seconds INTEGER NOT NULL DEFAULT 0,question_limit INTEGER NOT NULL DEFAULT 0,
 passing_percentage NUMERIC(5,2) NOT NULL DEFAULT 40,attempt_limit INTEGER NOT NULL DEFAULT 0,
 random_questions BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS questions(id BIGSERIAL PRIMARY KEY,question TEXT NOT NULL,option_a TEXT NOT NULL,option_b TEXT NOT NULL,option_c TEXT NOT NULL,option_d TEXT NOT NULL,answer CHAR(1) NOT NULL);
ALTER TABLE questions ADD COLUMN IF NOT EXISTS exam_id BIGINT;
ALTER TABLE questions ADD COLUMN IF NOT EXISTS question_seconds INTEGER;
CREATE INDEX IF NOT EXISTS idx_questions_exam ON questions(exam_id,id);
CREATE TABLE IF NOT EXISTS results(id BIGSERIAL PRIMARY KEY,student_id BIGINT,name TEXT NOT NULL,father_name TEXT NOT NULL,mobile TEXT NOT NULL,score INTEGER NOT NULL,total INTEGER NOT NULL,percentage NUMERIC(6,2) NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());
ALTER TABLE results ADD COLUMN IF NOT EXISTS review_json JSONB;
ALTER TABLE results ADD COLUMN IF NOT EXISTS exam_id BIGINT;
ALTER TABLE results ADD COLUMN IF NOT EXISTS exam_name TEXT;
ALTER TABLE results DROP CONSTRAINT IF EXISTS results_mobile_key;
CREATE INDEX IF NOT EXISTS idx_results_mobile_created ON results(mobile,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_results_exam_created ON results(exam_id,created_at DESC);
CREATE TABLE IF NOT EXISTS exam_sessions(
 id BIGSERIAL PRIMARY KEY,token TEXT UNIQUE NOT NULL,student_id BIGINT NOT NULL,exam_id BIGINT NOT NULL,
 started_at TIMESTAMPTZ DEFAULT NOW(),expires_at TIMESTAMPTZ,question_ids JSONB NOT NULL,submitted_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_sessions_student_exam ON exam_sessions(student_id,exam_id,started_at DESC);
CREATE TABLE IF NOT EXISTS pin_reset_requests(id BIGSERIAL PRIMARY KEY,student_id BIGINT,mobile TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',requested_at TIMESTAMPTZ DEFAULT NOW(),resolved_at TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_pin_reset_status ON pin_reset_requests(status,requested_at DESC);
CREATE TABLE IF NOT EXISTS admins(
 id BIGSERIAL PRIMARY KEY,admin_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL DEFAULT 'Administrator',email TEXT,
 password_hash TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS admin_password_resets(
 id BIGSERIAL PRIMARY KEY,admin_id TEXT NOT NULL,token_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_admin_reset_token ON admin_password_resets(token_hash,expires_at);
CREATE TABLE IF NOT EXISTS promotions(
 id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,subtitle TEXT,details TEXT,link_text TEXT,link_url TEXT,
 active BOOLEAN NOT NULL DEFAULT TRUE,sort_order INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
`);
const envAdminId=norm(process.env.ADMIN_ID),envAdminPassword=String(process.env.ADMIN_PASSWORD||''),envAdminEmail=norm(process.env.ADMIN_EMAIL);
if(envAdminId&&envAdminPassword){const a=await pool.query('SELECT id,email FROM admins WHERE admin_id=$1',[envAdminId]);if(!a.rowCount){const ph=await bcrypt.hash(envAdminPassword,12);await pool.query('INSERT INTO admins(admin_id,name,email,password_hash) VALUES($1,$2,$3,$4)',[envAdminId,'Super Admin',envAdminEmail||null,ph]);console.log('Initial admin account created from Render environment.')}else if(envAdminEmail&&!a.rows[0].email){await pool.query('UPDATE admins SET email=$1,updated_at=NOW() WHERE admin_id=$2',[envAdminEmail,envAdminId])}}
const pc=await pool.query('SELECT COUNT(*)::int n FROM promotions');if(!pc.rows[0].n){await pool.query(`INSERT INTO promotions(title,subtitle,details,link_text,link_url,sort_order) VALUES
('Admissions Open','CIE Computer Courses','New batch admissions are open. Contact CIE for course and enrollment details.','Visit CIE','https://cie.co.in',1),
('CIE Online Contest','Learn • Compete • Grow','Participate in online tests through the CIE Exam App and view your result instantly.','View Exams','#upcoming-exams',2),
('Institute / Franchise Promotion','Grow with CIE','Use this promotion area for CIE announcements, admissions, contests and institute promotions.','','',3)`)}

const ex=await pool.query('SELECT id FROM exams ORDER BY id LIMIT 1');
let legacyId;
if(!ex.rowCount){legacyId=(await pool.query(`INSERT INTO exams(name,timer_mode,passing_percentage,attempt_limit,active) VALUES('Legacy / General Exam','none',40,0,true) RETURNING id`)).rows[0].id}else legacyId=ex.rows[0].id;
await pool.query('UPDATE questions SET exam_id=$1 WHERE exam_id IS NULL',[legacyId]);
}

app.use(cors());app.use(express.json({limit:'3mb'}));

// Public website + secure Admin Portal
app.get('/admin',async(req,res)=>{if(!currentAdmin(req))return res.sendFile(path.join(__dirname,'public','admin-login.html'));res.sendFile(path.join(__dirname,'admin','index.html'))});
app.get('/admin/login',(req,res)=>res.sendFile(path.join(__dirname,'public','admin-login.html')));
app.get('/admin/reset',(req,res)=>res.sendFile(path.join(__dirname,'public','admin-reset.html')));
app.get('/download-app',(req,res)=>{const f=path.join(__dirname,'public','downloads','CIE_Online_Exam.apk');if(fs.existsSync(f))return res.download(f,'CIE_Online_Exam.apk');res.status(404).send('<h2>CIE Exam App APK is being updated.</h2><p>Please check again shortly.</p>')});
app.use(express.static(path.join(__dirname,'public')));

app.get('/api/public/exams',async(req,res)=>{try{if(!useDb)return res.json([]);const q=await pool.query(`SELECT id,name,start_at AS "startAt",end_at AS "endAt",timer_mode AS "timerMode",duration_minutes AS "durationMinutes",per_question_seconds AS "perQuestionSeconds",question_limit AS "questionLimit",passing_percentage AS "passingPercentage",attempt_limit AS "attemptLimit",random_questions AS "randomQuestions",active FROM exams WHERE active=true ORDER BY CASE WHEN start_at IS NULL THEN 1 ELSE 0 END,start_at ASC,id DESC LIMIT 12`);res.json(q.rows.map(x=>({...x,status:nowStatus(examPublic(x))})))}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/public/promotions',async(req,res)=>{try{if(!useDb)return res.json([]);const q=await pool.query('SELECT id,title,subtitle,details,link_text AS "linkText",link_url AS "linkUrl" FROM promotions WHERE active=true ORDER BY sort_order,id');res.json(q.rows)}catch(e){res.status(500).json({error:e.message})}});

app.post('/api/admin/auth/login',async(req,res)=>{try{if(!useDb)return res.status(503).json({error:'Database required.'});const adminId=norm(req.body?.adminId),password=String(req.body?.password||'');if(!adminId||!password)return res.status(400).json({error:'Enter Admin ID and Password.'});const q=await pool.query('SELECT admin_id,password_hash,active FROM admins WHERE admin_id=$1',[adminId]);if(!q.rowCount||!q.rows[0].active||!(await bcrypt.compare(password,q.rows[0].password_hash)))return res.status(401).json({error:'Admin ID or Password is incorrect.'});setAdminCookie(res,q.rows[0].admin_id);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/auth/logout',(req,res)=>{clearAdminCookie(res);res.json({ok:true})});
app.get('/api/admin/auth/me',requireAdmin,async(req,res)=>{try{const q=await pool.query('SELECT admin_id AS "adminId",name,email FROM admins WHERE admin_id=$1',[req.admin.adminId]);res.json(q.rows[0]||{})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/auth/forgot',async(req,res)=>{try{if(!useDb)return res.status(503).json({error:'Database required.'});const adminId=norm(req.body?.adminId),email=norm(req.body?.email).toLowerCase();if(!adminId||!email)return res.status(400).json({error:'Enter Admin ID and registered Email.'});const q=await pool.query('SELECT admin_id,email FROM admins WHERE admin_id=$1 AND LOWER(email)=LOWER($2) AND active=true',[adminId,email]);if(!q.rowCount)return res.status(404).json({error:'Admin ID and Email do not match.'});const token=crypto.randomBytes(32).toString('hex'),hash=crypto.createHash('sha256').update(token).digest('hex');await pool.query('DELETE FROM admin_password_resets WHERE admin_id=$1 OR expires_at<NOW()',[adminId]);await pool.query("INSERT INTO admin_password_resets(admin_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '20 minutes')",[adminId,hash]);const resetUrl=`${req.protocol}://${req.get('host')}/admin/reset?token=${encodeURIComponent(token)}`;await sendAdminResetEmail(email,resetUrl);res.json({ok:true,message:'Password reset link sent to registered email.'})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/admin/auth/reset',async(req,res)=>{try{const token=String(req.body?.token||''),newPassword=String(req.body?.newPassword||'');if(token.length<20||newPassword.length<8)return res.status(400).json({error:'Invalid reset link or password must be at least 8 characters.'});const hash=crypto.createHash('sha256').update(token).digest('hex');const q=await pool.query('SELECT id,admin_id FROM admin_password_resets WHERE token_hash=$1 AND used_at IS NULL AND expires_at>NOW()',[hash]);if(!q.rowCount)return res.status(400).json({error:'Reset link is invalid or expired.'});const ph=await bcrypt.hash(newPassword,12);const c=await pool.connect();try{await c.query('BEGIN');await c.query('UPDATE admins SET password_hash=$1,updated_at=NOW() WHERE admin_id=$2',[ph,q.rows[0].admin_id]);await c.query('UPDATE admin_password_resets SET used_at=NOW() WHERE id=$1',[q.rows[0].id]);await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}res.json({ok:true,message:'Password updated. You can login now.'})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/auth/change-password',requireAdmin,async(req,res)=>{try{const oldPassword=String(req.body?.oldPassword||''),newPassword=String(req.body?.newPassword||'');if(newPassword.length<8)return res.status(400).json({error:'New password must be at least 8 characters.'});const q=await pool.query('SELECT password_hash FROM admins WHERE admin_id=$1',[req.admin.adminId]);if(!q.rowCount||!(await bcrypt.compare(oldPassword,q.rows[0].password_hash)))return res.status(401).json({error:'Current password is incorrect.'});const ph=await bcrypt.hash(newPassword,12);await pool.query('UPDATE admins SET password_hash=$1,updated_at=NOW() WHERE admin_id=$2',[ph,req.admin.adminId]);res.json({ok:true,message:'Password changed successfully.'})}catch(e){res.status(500).json({error:e.message})}});

// All admin data/actions below require a valid admin session.
app.use('/api/admin',(req,res,next)=>{if(req.path.startsWith('/auth/'))return next();return requireAdmin(req,res,next)});
app.use('/api/results',requireAdmin);
app.get('/api/health',(req,res)=>res.json({ok:true,mode:useDb?'postgres':'local-json',version:'3.3'}));

app.post('/api/register',async(req,res)=>{try{const b=req.body||{},name=norm(b.name),fatherName=norm(b.fatherName),mobile=norm(b.mobile),pin=String(b.pin||'');if(!validFullName(name))return res.status(400).json({error:'Enter full Student Name using letters only (at least 2 words).'});if(!validFullName(fatherName))return res.status(400).json({error:'Enter full Father Name using letters only (at least 2 words).'});if(!validMobile(mobile))return res.status(400).json({error:'Mobile Number must be exactly 10 digits.'});if(!validPin(pin))return res.status(400).json({error:'PIN must be exactly 4 digits.'});const pinHash=await bcrypt.hash(pin,10);if(useDb){const q=await pool.query('INSERT INTO students(name,father_name,mobile,pin_hash) VALUES($1,$2,$3,$4) ON CONFLICT(mobile) DO NOTHING RETURNING id,name,father_name,mobile,pin_hash',[name,fatherName,mobile,pinHash]);if(!q.rowCount)return res.status(409).json({error:'Mobile already registered. Please Login.'});return res.json({ok:true,student:studentPublic(q.rows[0])})}const s=readLocal('students.json');if(s.some(x=>String(x.mobile)===mobile))return res.status(409).json({error:'Mobile already registered. Please Login.'});const x={id:Date.now(),name,fatherName,mobile,pinHash,createdAt:new Date().toISOString()};s.push(x);writeLocal('students.json',s);res.json({ok:true,student:studentPublic(x)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/login',async(req,res)=>{try{const mobile=norm(req.body?.mobile),pin=String(req.body?.pin||'');if(!validMobile(mobile)||!validPin(pin))return res.status(400).json({error:'Enter 10-digit Mobile Number and 4-digit PIN.'});const s=await verifyStudent(mobile,pin);if(!s)return res.status(401).json({error:'Mobile Number or PIN is incorrect.'});res.json({ok:true,student:studentPublic(s)})}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/forgot-pin',async(req,res)=>{try{const mobile=norm(req.body?.mobile);if(!validMobile(mobile))return res.status(400).json({error:'Enter a valid 10-digit Mobile Number.'});if(useDb){const s=await pool.query('SELECT id FROM students WHERE mobile=$1',[mobile]);if(!s.rowCount)return res.status(404).json({error:'Mobile Number is not registered.'});const p=await pool.query("SELECT id FROM pin_reset_requests WHERE mobile=$1 AND status='PENDING' LIMIT 1",[mobile]);if(!p.rowCount)await pool.query('INSERT INTO pin_reset_requests(student_id,mobile) VALUES($1,$2)',[s.rows[0].id,mobile]);return res.json({ok:true,message:'PIN reset request sent to Admin.'})}const students=readLocal('students.json'),s=students.find(x=>String(x.mobile)===mobile);if(!s)return res.status(404).json({error:'Mobile Number is not registered.'});const rr=readLocal('pin_reset_requests.json');if(!rr.some(x=>x.mobile===mobile&&x.status==='PENDING'))rr.push({id:Date.now(),studentId:s.id,mobile,status:'PENDING',requestedAt:new Date().toISOString()});writeLocal('pin_reset_requests.json',rr);res.json({ok:true,message:'PIN reset request sent to Admin.'})}catch(e){res.status(500).json({error:e.message})}});

app.post('/api/exams/available',async(req,res)=>{try{const student=await verifyStudent(norm(req.body?.mobile),String(req.body?.pin||''));if(!student)return res.status(401).json({error:'Invalid login.'});if(!useDb)return res.json([]);const q=await pool.query(`SELECT e.*,(SELECT COUNT(*)::int FROM questions q WHERE q.exam_id=e.id) question_count,(SELECT COUNT(*)::int FROM results r WHERE r.exam_id=e.id AND r.student_id=$1) attempts_used FROM exams e ORDER BY COALESCE(e.start_at,e.created_at) DESC,e.id DESC`,[student.id]);res.json(q.rows.map(r=>{const e=examPublic(r);return{...e,status:nowStatus(e),questionCount:Number(r.question_count),attemptsUsed:Number(r.attempts_used),attemptsRemaining:e.attemptLimit===0?null:Math.max(0,e.attemptLimit-Number(r.attempts_used))}}))}catch(e){res.status(500).json({error:e.message})}});

app.post('/api/exams/:id/start',async(req,res)=>{try{if(!useDb)return res.status(501).json({error:'V3.2 exam mode requires database.'});const student=await verifyStudent(norm(req.body?.mobile),String(req.body?.pin||''));if(!student)return res.status(401).json({error:'Invalid login.'});const id=String(req.params.id);if(!/^\d+$/.test(id))return res.status(400).json({error:'Invalid exam.'});const er=await pool.query('SELECT * FROM exams WHERE id=$1',[id]);if(!er.rowCount)return res.status(404).json({error:'Exam not found.'});const e=examPublic(er.rows[0]),st=nowStatus(e);if(st==='inactive')return res.status(403).json({error:'This exam is inactive.'});if(st==='upcoming')return res.status(403).json({error:'This exam has not started yet.'});if(st==='ended')return res.status(403).json({error:'This exam has ended.'});const used=Number((await pool.query('SELECT COUNT(*)::int c FROM results WHERE exam_id=$1 AND student_id=$2',[id,student.id])).rows[0].c);if(e.attemptLimit>0&&used>=e.attemptLimit)return res.status(403).json({error:'Your attempt limit for this exam is complete.'});let sql=`SELECT id,question,option_a AS a,option_b AS b,option_c AS c,option_d AS d,COALESCE(question_seconds,0) AS "questionSeconds" FROM questions WHERE exam_id=$1`;sql+=e.randomQuestions?' ORDER BY RANDOM()':' ORDER BY id';const params=[id];if(e.questionLimit>0){params.push(e.questionLimit);sql+=` LIMIT $${params.length}`}const qs=(await pool.query(sql,params)).rows;if(!qs.length)return res.status(400).json({error:'No questions uploaded for this exam.'});let expiresAt=null;const now=Date.now();if((e.timerMode==='whole'||e.timerMode==='both')&&e.durationMinutes>0)expiresAt=new Date(now+e.durationMinutes*60000);if(e.endAt){const end=new Date(e.endAt);if(!expiresAt||end<expiresAt)expiresAt=end}const token=randomToken();await pool.query('INSERT INTO exam_sessions(token,student_id,exam_id,expires_at,question_ids) VALUES($1,$2,$3,$4,$5::jsonb)',[token,student.id,id,expiresAt,JSON.stringify(qs.map(x=>Number(x.id)))]);res.json({sessionToken:token,exam:e,expiresAt:expiresAt?expiresAt.toISOString():null,questions:qs,attemptNumber:used+1})}catch(e){res.status(500).json({error:e.message})}});

app.post('/api/result',async(req,res)=>{try{const b=req.body||{},mobile=norm(b.mobile),pin=String(b.pin||''),student=await verifyStudent(mobile,pin);if(!student)return res.status(401).json({error:'Student login verification failed.'});if(useDb&&b.sessionToken){const sr=await pool.query(`SELECT s.*,e.name,e.passing_percentage,e.timer_mode,e.per_question_seconds FROM exam_sessions s JOIN exams e ON e.id=s.exam_id WHERE s.token=$1 AND s.student_id=$2`,[String(b.sessionToken),student.id]);if(!sr.rowCount)return res.status(400).json({error:'Invalid exam session.'});const ses=sr.rows[0];if(ses.submitted_at)return res.status(409).json({error:'This exam attempt is already submitted.'});const ids=Array.isArray(ses.question_ids)?ses.question_ids:JSON.parse(ses.question_ids||'[]');const submitted=Array.isArray(b.answers)?b.answers.map(v=>Number.isInteger(Number(v))?Number(v):-1):[];if(submitted.length!==ids.length)return res.status(400).json({error:'Answer count does not match this exam.'});const qr=await pool.query(`SELECT id,question,option_a AS a,option_b AS b,option_c AS c,option_d AS d,answer FROM questions WHERE id=ANY($1::bigint[])`,[ids]);const map=new Map(qr.rows.map(x=>[Number(x.id),x]));let score=0;const review=ids.map((qid,i)=>{const q=map.get(Number(qid));if(!q)return null;const si=submitted[i]>=0&&submitted[i]<=3?submitted[i]:-1,ci='ABCD'.indexOf(String(q.answer||'').toUpperCase());if(si===ci&&ci>=0)score++;return{question:q.question,a:q.a,b:q.b,c:q.c,d:q.d,selected:si>=0?'ABCD'[si]:'',correct:ci>=0?'ABCD'[ci]:'',isCorrect:si===ci&&ci>=0}}).filter(Boolean);const total=review.length,pct=total?+(score*100/total).toFixed(2):0,status=pct>=Number(ses.passing_percentage||40)?'PASS':'FAIL';const fatherName=student.father_name;const c=await pool.connect();try{await c.query('BEGIN');const r=await c.query(`INSERT INTO results(student_id,name,father_name,mobile,score,total,percentage,status,review_json,exam_id,exam_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,$10,$11) RETURNING id,student_id AS "studentId",name,father_name AS "fatherName",mobile,score,total,percentage,status,review_json AS review,exam_id AS "examId",exam_name AS "examName",created_at AS "createdAt"`,[student.id,student.name,fatherName,mobile,score,total,pct,status,JSON.stringify(review),ses.exam_id,ses.name]);await c.query('UPDATE exam_sessions SET submitted_at=NOW() WHERE id=$1',[ses.id]);await c.query('COMMIT');return res.json(r.rows[0])}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
// Compatibility for old V3.1 APK
let score=0,total=0,review=null;if(Array.isArray(b.answers)){const qs=useDb?(await pool.query('SELECT id,question,option_a AS a,option_b AS b,option_c AS c,option_d AS d,answer FROM questions ORDER BY id')).rows:readLocal('questions.json');const submitted=b.answers.map(v=>Number.isInteger(Number(v))?Number(v):-1);total=qs.length;review=qs.map((q,i)=>{const si=submitted[i]>=0&&submitted[i]<=3?submitted[i]:-1,ci='ABCD'.indexOf(String(q.answer||'').toUpperCase());if(si===ci&&ci>=0)score++;return{question:q.question,a:q.a,b:q.b,c:q.c,d:q.d,selected:si>=0?'ABCD'[si]:'',correct:ci>=0?'ABCD'[ci]:'',isCorrect:si===ci&&ci>=0}})}else{total=Math.max(0,Number(b.total)||0);score=Math.max(0,Number(b.score)||0)}const pct=total?+(score*100/total).toFixed(2):0,status=pct>=40?'PASS':'FAIL';if(useDb){const r=await pool.query(`INSERT INTO results(student_id,name,father_name,mobile,score,total,percentage,status,review_json,exam_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,'Legacy App Attempt') RETURNING id,score,total,percentage,status,review_json AS review,exam_name AS "examName",created_at AS "createdAt"`,[student.id,student.name,student.father_name,mobile,score,total,pct,status,review?JSON.stringify(review):null]);return res.json(r.rows[0])}res.status(501).json({error:'Local V3.2 result mode not supported.'})}catch(e){res.status(500).json({error:e.message})}});

app.post('/api/my-results',async(req,res)=>{try{const student=await verifyStudent(norm(req.body?.mobile),String(req.body?.pin||''));if(!student)return res.status(401).json({error:'Invalid Mobile Number or PIN.'});if(useDb){const q=await pool.query(`SELECT id,score,total,percentage,status,review_json AS review,exam_id AS "examId",COALESCE(exam_name,'Old Exam') AS "examName",created_at AS "createdAt" FROM results WHERE mobile=$1 ORDER BY created_at DESC,id DESC`,[student.mobile]);return res.json({student:studentPublic(student),results:q.rows})}res.json({student:studentPublic(student),results:readLocal('results.json').filter(x=>String(x.mobile)===student.mobile)})}catch(e){res.status(500).json({error:e.message})}});

// Compatibility endpoint for V3.1 APK while V3.2 is being installed.
app.get('/api/questions',async(req,res)=>{try{if(!useDb)return res.json(readLocal('questions.json'));const ex=await pool.query(`SELECT id FROM exams WHERE active=true ORDER BY id LIMIT 1`);if(!ex.rowCount)return res.json([]);const q=await pool.query(`SELECT id,question,option_a AS a,option_b AS b,option_c AS c,option_d AS d,answer FROM questions WHERE exam_id=$1 ORDER BY id`,[ex.rows[0].id]);res.json(q.rows)}catch(e){res.status(500).json({error:e.message})}});

// Admin exams
app.get('/api/admin/exams',async(req,res)=>{try{if(!useDb)return res.json(readLocal('exams.json'));const q=await pool.query(`SELECT e.*,(SELECT COUNT(*)::int FROM questions q WHERE q.exam_id=e.id) question_count,(SELECT COUNT(*)::int FROM results r WHERE r.exam_id=e.id) result_count FROM exams e ORDER BY e.created_at DESC,e.id DESC`);res.json(q.rows.map(r=>({...examPublic(r),questionCount:Number(r.question_count),resultCount:Number(r.result_count),status:nowStatus(examPublic(r))})))}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/exams',async(req,res)=>{try{if(!useDb)return res.status(501).json({error:'Database required.'});const b=req.body||{},name=norm(b.name),timerMode=String(b.timerMode||'none');if(!name)return res.status(400).json({error:'Exam Name is required.'});if(!['none','whole','per_question','both'].includes(timerMode))return res.status(400).json({error:'Invalid timer mode.'});const duration=clampInt(b.durationMinutes,0,1440,0),per=clampInt(b.perQuestionSeconds,0,3600,0),ql=clampInt(b.questionLimit,0,1000,0),pass=Math.max(0,Math.min(100,Number(b.passingPercentage)||40)),attempt=clampInt(b.attemptLimit,0,100,0);if((timerMode==='whole'||timerMode==='both')&&duration<1)return res.status(400).json({error:'Whole paper timer needs Duration Minutes.'});if((timerMode==='per_question'||timerMode==='both')&&per<1)return res.status(400).json({error:'Per Question timer needs seconds.'});const start=b.startAt?new Date(b.startAt):null,end=b.endAt?new Date(b.endAt):null;if(start&&isNaN(start))return res.status(400).json({error:'Invalid start date/time.'});if(end&&isNaN(end))return res.status(400).json({error:'Invalid end date/time.'});if(start&&end&&end<=start)return res.status(400).json({error:'End time must be after Start time.'});const q=await pool.query(`INSERT INTO exams(name,start_at,end_at,timer_mode,duration_minutes,per_question_seconds,question_limit,passing_percentage,attempt_limit,random_questions,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[name,start,end,timerMode,duration,per,ql,pass,attempt,!!b.randomQuestions,b.active!==false]);res.json(examPublic(q.rows[0]))}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/admin/exams/:id',async(req,res)=>{try{if(!useDb)return res.status(501).json({error:'Database required.'});const id=req.params.id,b=req.body||{},name=norm(b.name),timerMode=String(b.timerMode||'none');if(!/^\d+$/.test(id)||!name)return res.status(400).json({error:'Invalid exam data.'});const duration=clampInt(b.durationMinutes,0,1440,0),per=clampInt(b.perQuestionSeconds,0,3600,0),ql=clampInt(b.questionLimit,0,1000,0),pass=Math.max(0,Math.min(100,Number(b.passingPercentage)||40)),attempt=clampInt(b.attemptLimit,0,100,0);if((timerMode==='whole'||timerMode==='both')&&duration<1)return res.status(400).json({error:'Duration Minutes required.'});if((timerMode==='per_question'||timerMode==='both')&&per<1)return res.status(400).json({error:'Per Question Seconds required.'});const start=b.startAt?new Date(b.startAt):null,end=b.endAt?new Date(b.endAt):null;const q=await pool.query(`UPDATE exams SET name=$1,start_at=$2,end_at=$3,timer_mode=$4,duration_minutes=$5,per_question_seconds=$6,question_limit=$7,passing_percentage=$8,attempt_limit=$9,random_questions=$10,active=$11 WHERE id=$12 RETURNING *`,[name,start,end,timerMode,duration,per,ql,pass,attempt,!!b.randomQuestions,b.active!==false,id]);if(!q.rowCount)return res.status(404).json({error:'Exam not found.'});res.json(examPublic(q.rows[0]))}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/admin/exams/:id',async(req,res)=>{try{if(!useDb)return res.status(501).json({error:'Database required.'});const id=req.params.id;if(!/^\d+$/.test(id))return res.status(400).json({error:'Invalid exam id.'});const counts=await pool.query('SELECT (SELECT COUNT(*) FROM results WHERE exam_id=$1) results,(SELECT COUNT(*) FROM questions WHERE exam_id=$1) questions',[id]);if(Number(counts.rows[0].results)>0)return res.status(409).json({error:'This exam has results. Delete its results first or set exam Inactive.'});await pool.query('DELETE FROM exam_sessions WHERE exam_id=$1',[id]);await pool.query('DELETE FROM questions WHERE exam_id=$1',[id]);const q=await pool.query('DELETE FROM exams WHERE id=$1 RETURNING id',[id]);if(!q.rowCount)return res.status(404).json({error:'Exam not found.'});res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/admin/questions',async(req,res)=>{try{if(!useDb)return res.json(readLocal('questions.json'));const examId=norm(req.query.examId);if(!/^\d+$/.test(examId))return res.status(400).json({error:'Select exam.'});const q=await pool.query(`SELECT id,question,option_a AS a,option_b AS b,option_c AS c,option_d AS d,answer,COALESCE(question_seconds,0) AS "questionSeconds" FROM questions WHERE exam_id=$1 ORDER BY id`,[examId]);res.json(q.rows)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/upload-excel',upload.single('file'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Select Excel'});try{if(!useDb)throw new Error('Database required for V3.2');const examId=norm(req.body?.examId);if(!/^\d+$/.test(examId))throw new Error('Select Exam before upload');const ex=await pool.query('SELECT id FROM exams WHERE id=$1',[examId]);if(!ex.rowCount)throw new Error('Exam not found');const wb=XLSX.readFile(req.file.path),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''}),errors=[],valid=[];rows.forEach((z,i)=>{const n=i+2,question=norm(z.Question),a=norm(z['Option A']),b=norm(z['Option B']),c=norm(z['Option C']),d=norm(z['Option D']),raw=norm(z.Answer).toUpperCase(),answer=({'1':'A','2':'B','3':'C','4':'D'}[raw]||raw),qsec=clampInt(z['Time Seconds']||z['Question Seconds'],0,3600,0);if(!question)errors.push(`Row ${n}: Question missing`);if(!a)errors.push(`Row ${n}: Option A missing`);if(!b)errors.push(`Row ${n}: Option B missing`);if(!c)errors.push(`Row ${n}: Option C missing`);if(!d)errors.push(`Row ${n}: Option D missing`);if(!['A','B','C','D'].includes(answer))errors.push(`Row ${n}: Answer must be A/B/C/D or 1/2/3/4`);if(question&&a&&b&&c&&d&&['A','B','C','D'].includes(answer))valid.push({question,a,b,c,d,answer,qsec})});for(const x of valid)await pool.query('INSERT INTO questions(exam_id,question,option_a,option_b,option_c,option_d,answer,question_seconds) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[examId,x.question,x.a,x.b,x.c,x.d,x.answer,x.qsec||null]);fs.unlinkSync(req.file.path);res.json({found:rows.length,imported:valid.length,errors})}catch(e){try{fs.unlinkSync(req.file.path)}catch{}res.status(400).json({error:e.message})}});
app.post('/api/admin/clear-questions',async(req,res)=>{try{const id=norm(req.body?.examId);if(!/^\d+$/.test(id))return res.status(400).json({error:'Select exam.'});if(useDb)await pool.query('DELETE FROM questions WHERE exam_id=$1',[id]);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});


app.get('/api/admin/promotions',async(req,res)=>{try{const q=await pool.query('SELECT id,title,subtitle,details,link_text AS "linkText",link_url AS "linkUrl",active,sort_order AS "sortOrder" FROM promotions ORDER BY sort_order,id');res.json(q.rows)}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/promotions',async(req,res)=>{try{const b=req.body||{},title=norm(b.title);if(!title)return res.status(400).json({error:'Promotion title required.'});const q=await pool.query('INSERT INTO promotions(title,subtitle,details,link_text,link_url,active,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[title,norm(b.subtitle),norm(b.details),norm(b.linkText),norm(b.linkUrl),b.active!==false,clampInt(b.sortOrder,0,999,0)]);res.json({ok:true,id:q.rows[0].id})}catch(e){res.status(500).json({error:e.message})}});
app.put('/api/admin/promotions/:id',async(req,res)=>{try{const id=req.params.id,b=req.body||{},title=norm(b.title);if(!/^\d+$/.test(id)||!title)return res.status(400).json({error:'Invalid promotion.'});await pool.query('UPDATE promotions SET title=$1,subtitle=$2,details=$3,link_text=$4,link_url=$5,active=$6,sort_order=$7,updated_at=NOW() WHERE id=$8',[title,norm(b.subtitle),norm(b.details),norm(b.linkText),norm(b.linkUrl),b.active!==false,clampInt(b.sortOrder,0,999,0),id]);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/admin/promotions/:id',async(req,res)=>{try{if(!/^\d+$/.test(req.params.id))return res.status(400).json({error:'Invalid promotion.'});await pool.query('DELETE FROM promotions WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});

app.get('/api/results',async(req,res)=>{try{if(!useDb)return res.json(readLocal('results.json'));const from=norm(req.query.from),to=norm(req.query.to),examId=norm(req.query.examId),validDate=x=>/^\d{4}-\d{2}-\d{2}$/.test(x);if((from&&!validDate(from))||(to&&!validDate(to)))return res.status(400).json({error:'Date must be YYYY-MM-DD'});let sql=`SELECT id,student_id AS "studentId",name,father_name AS "fatherName",mobile,score,total,percentage,status,exam_id AS "examId",COALESCE(exam_name,'Old Exam') AS "examName",created_at AS "createdAt" FROM results`,params=[],w=[];if(from){params.push(from);w.push(`created_at >= ($${params.length}::date AT TIME ZONE 'Asia/Kolkata')`)}if(to){params.push(to);w.push(`created_at < (($${params.length}::date + 1) AT TIME ZONE 'Asia/Kolkata')`)}if(examId){if(!/^\d+$/.test(examId))return res.status(400).json({error:'Invalid exam.'});params.push(examId);w.push(`exam_id=$${params.length}`)}if(w.length)sql+=' WHERE '+w.join(' AND ');sql+=' ORDER BY created_at DESC,id DESC';res.json((await pool.query(sql,params)).rows)}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/students',async(req,res)=>{try{if(useDb){const q=await pool.query(`SELECT id,name,father_name AS "fatherName",mobile,(pin_hash IS NOT NULL) AS "pinSet",created_at AS "createdAt" FROM students ORDER BY created_at DESC,id DESC`);return res.json(q.rows)}res.json(readLocal('students.json').map(x=>({id:x.id,name:x.name,fatherName:x.fatherName,mobile:x.mobile,pinSet:!!x.pinHash,createdAt:x.createdAt})))}catch(e){res.status(500).json({error:e.message})}});
app.get('/api/admin/pin-reset-requests',async(req,res)=>{try{if(useDb){const q=await pool.query(`SELECT r.id,r.student_id AS "studentId",r.mobile,r.status,r.requested_at AS "requestedAt",r.resolved_at AS "resolvedAt",s.name,s.father_name AS "fatherName" FROM pin_reset_requests r LEFT JOIN students s ON s.id=r.student_id ORDER BY CASE WHEN r.status='PENDING' THEN 0 ELSE 1 END,r.requested_at DESC`);return res.json(q.rows)}res.json([])}catch(e){res.status(500).json({error:e.message})}});
app.post('/api/admin/reset-pin',async(req,res)=>{try{const requestId=req.body?.requestId,studentId=req.body?.studentId,mobile=norm(req.body?.mobile),newPin=String(req.body?.newPin||'');if(!validPin(newPin))return res.status(400).json({error:'New PIN must be exactly 4 digits.'});const hash=await bcrypt.hash(newPin,10);if(useDb){let q;if(studentId)q=await pool.query('UPDATE students SET pin_hash=$1 WHERE id=$2 RETURNING id,mobile',[hash,studentId]);else q=await pool.query('UPDATE students SET pin_hash=$1 WHERE mobile=$2 RETURNING id,mobile',[hash,mobile]);if(!q.rowCount)return res.status(404).json({error:'Student not found.'});if(requestId)await pool.query("UPDATE pin_reset_requests SET status='RESOLVED',resolved_at=NOW() WHERE id=$1",[requestId]);else await pool.query("UPDATE pin_reset_requests SET status='RESOLVED',resolved_at=NOW() WHERE mobile=$1 AND status='PENDING'",[q.rows[0].mobile]);return res.json({ok:true,message:'PIN has been set/reset successfully.'})}res.status(501).json({error:'Database required.'})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/admin/results/:id',async(req,res)=>{try{const id=req.params.id;if(!/^\d+$/.test(id))return res.status(400).json({error:'Invalid result id.'});if(useDb){const q=await pool.query('DELETE FROM results WHERE id=$1 RETURNING id',[id]);if(!q.rowCount)return res.status(404).json({error:'Result not found.'});return res.json({ok:true,message:'Result deleted.'})}res.status(501).json({error:'Database required.'})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/admin/students/:id',async(req,res)=>{try{const id=req.params.id;if(!/^\d+$/.test(id))return res.status(400).json({error:'Invalid student id.'});if(!useDb)return res.status(501).json({error:'Database required.'});const c=await pool.connect();try{await c.query('BEGIN');const st=await c.query('SELECT mobile FROM students WHERE id=$1',[id]);if(!st.rowCount){await c.query('ROLLBACK');return res.status(404).json({error:'Student not found.'})}const mobile=st.rows[0].mobile;await c.query('DELETE FROM exam_sessions WHERE student_id=$1',[id]);await c.query('DELETE FROM pin_reset_requests WHERE student_id=$1 OR mobile=$2',[id,mobile]);await c.query('DELETE FROM results WHERE student_id=$1 OR mobile=$2',[id,mobile]);await c.query('DELETE FROM students WHERE id=$1',[id]);await c.query('COMMIT');res.json({ok:true,message:'Student and linked data deleted.'})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}catch(e){res.status(500).json({error:e.message})}});

initDb().then(()=>app.listen(PORT,()=>console.log(`CIE Exam Admin running on port ${PORT} (${useDb?'Postgres':'local JSON'}) - V3.3`))).catch(err=>{console.error('Database startup error:',err);process.exit(1)});
