document.addEventListener('DOMContentLoaded',()=>{const pages=[
['/admin','Dashboard','⌂'],['/admin/exams','Exams','▣'],['/admin/results','Results','✓'],['/admin/students','Students & WhatsApp','♟'],['/admin/pin-reset','PIN Reset','⌁'],['/admin/promotions','Promotions','◇'],['/admin/old-papers','Old Papers','▤'],['/admin/media','App & Thumbnails','▧'],['/admin/student-popup','Student Popup','▢']
];const path=location.pathname.replace(/\/$/,'')||'/';const active=pages.find(x=>x[0]===path)||pages[0];document.body.classList.add('cie-admin');const side=document.createElement('aside');side.className='cie-sidebar';side.innerHTML='<div class="cie-side-brand"><strong>CIE Admin Portal</strong><span>Examination Management</span></div><nav class="cie-side-nav">'+pages.map(([url,label,icon])=>'<a href="'+url+'" class="'+(url===active[0]?'active':'')+'"><span class="cie-icon">'+icon+'</span><span>'+label+'</span>'+(url==='/admin/pin-reset'?'<b id="ciePinBadge" class="cie-badge"></b>':'')+'</a>').join('')+'</nav>';document.body.prepend(side);
const top=document.createElement('div');top.className='cie-topbar';top.innerHTML='<div style="display:flex;align-items:center;gap:11px"><button class="cie-menu-btn" aria-label="Menu">☰</button><div><h1>'+active[1]+'</h1><small>CIE Exam Admin • V3.9.6</small></div></div><div class="cie-actions"><button class="cie-change">Change Password</button><button class="cie-logout">Logout</button></div>';document.body.prepend(top);
top.querySelector('.cie-menu-btn').onclick=()=>side.classList.toggle('open');document.addEventListener('click',e=>{if(innerWidth<=820&&!side.contains(e.target)&&!e.target.closest('.cie-menu-btn'))side.classList.remove('open')});
top.querySelector('.cie-logout').onclick=async()=>{try{await fetch('/api/admin/auth/logout',{method:'POST'})}finally{location.href='/admin'}};
top.querySelector('.cie-change').onclick=async()=>{const oldPassword=prompt('Current password');if(oldPassword===null)return;const newPassword=prompt('New password (minimum 8 characters)');if(newPassword===null)return;try{const r=await fetch('/api/admin/auth/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({oldPassword,newPassword})}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Password change failed');alert(j.message||'Password changed successfully.')}catch(e){alert(e.message)}};
fetch('/api/admin/pin-reset-count').then(r=>r.ok?r.json():null).then(j=>{const b=document.getElementById('ciePinBadge'),n=Number(j&&j.pending||0);if(b&&n){b.textContent=n>99?'99+':n;b.style.display='inline-flex'}}).catch(()=>{});
});
